# Site settings
title:          Syoo37 blog
description:    "Minimal Jekyll theme for storytellers"
# baseurl:        "/tale"
url:            "https://syoo37.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Soyoung
  url:          https://syoo37.github.io
  email:        s37__@naver.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post
  # remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
